version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Pacific/Auckland
    open-pull-requests-limit: 3
    groups:
      npm-minor-and-patch:
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: eslint
        update-types:
          - version-update:semver-major
    labels:
      - type:chore
      - area:workflow

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Pacific/Auckland
    open-pull-requests-limit: 2
    groups:
      github-actions-minor-and-patch:
        update-types:
          - minor
          - patch
    labels:
      - type:ci
      - area:workflow
